# data
data_dir: data/Wiki10-31K
data_name: Wiki10-31K
min_vocab_freq: 1
max_seq_length: 1000
fixed_length: True

# train
seed: 1337
epochs: 50
batch_size: 64
optimizer: adam
learning_rate: 0.0005
weight_decay: 0
patience: 5

# eval
eval_batch_size: 256
monitor_metrics: [P@1, P@3, P@5]
val_metric: Macro-F1

# model
model_name: XMLCNN
num_filter_per_size: 128 # filter channels
pool_size: 500
filter_sizes: [2, 4, 8]
hidden_dim: 512
dropout: 0.2
dropout2: 0.2

# pretrained vocab / embeddings
embed_file: glove.6B.300d
