# data
data_dir: data/Wiki10-31K
data_name: Wiki10-31K
min_vocab_freq: 1
max_seq_length: 1000
fixed_length: True

# train
seed: 1337
epochs: 100
batch_size: 64
optimizer: adam
learning_rate: ['choice', [0.001, 0.003, 0.0001, 0.0003]]
weight_decay: 0
patience: 5

# eval
eval_batch_size: 256
monitor_metrics: ['P@1','P@3','P@5']
val_metric: Macro-F1

# model
model_name: XMLCNN
num_filter_per_size: ['choice', [32, 64, 128, 256, 512]]
pool_size: ['choice', [100, 250, 500, 1000]]
filter_sizes: [2, 4, 8]
hidden_dim: ['choice', [128, 256, 512, 1024]]
dropout: ['choice', [0.2, 0.4, 0.6, 0.8]]
dropout2: ['choice', [0.2, 0.4, 0.6, 0.8]]

# other parameters specified in main.py::get_args
init_weight: kaiming_uniform
activation: relu
vocab_file: null
embed_file: glove.6B.300d
config: example_config/Wiki10-31K/xmlcnn_tune.yml
cpu: false
data_workers: 8
eval: false
label_file: null
load_checkpoint: null
metrics_thresholds: [0.5]
momentum: 0.9
predict_out_path: null
result_dir: runs/tune_wiki
test_path: null
train_path: null
val_path: null
val_size: 0.2
vocab_file: null
shuffle: true
